model_list:
  - model_name: antigravity-smart
    litellm_params:
      model: gemini/gemini-pro-latest
      api_key: AIzaSyA8QiDW3Hy5Lew7JTd75X3iYk-W2OGw33w
  - model_name: antigravity-fast
    litellm_params:
      model: gemini/gemini-flash-latest
      api_key: AIzaSyA8QiDW3Hy5Lew7JTd75X3iYk-W2OGw33w

general_settings:
  master_key: sk-antigravity-admin
  database_url: "postgresql://litellm_admin:sk-antigravity-db-pass@db:5432/litellm_db"

litellm_settings:
  drop_params: true
  set_verbose: true
  callbacks: ["acp_logging_handler.proxy_custom_logger"]
